import pytest
from unittest.mock import MagicMock, patch
from cfmanager.services.dns import DNSService
from cfmanager.core.exceptions import ValidationError


# ── Export ────────────────────────────────────────────────────────────────────

def test_export_records_csv_returns_header_and_rows(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)
    mock_records = [
        {"id": "r1", "name": "api.example.com", "type": "A", "content": "192.0.2.1", "ttl": 3600, "proxied": False, "comment": ""},
        {"id": "r2", "name": "www.example.com", "type": "CNAME", "content": "example.com", "ttl": 1, "proxied": True, "comment": "CDN"},
    ]
    service.list_dns_records = MagicMock(return_value=mock_records)

    result = service.export_records("zone_123", format="csv")

    lines = result.strip().splitlines()
    assert lines[0] == "name,type,content,ttl,proxied,comment"
    assert "api.example.com,A,192.0.2.1,3600,False," in result
    assert "www.example.com,CNAME,example.com,1,True,CDN" in result
    service.list_dns_records.assert_called_once_with("zone_123")


def test_export_records_bind_returns_zone_file_lines(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)
    mock_records = [
        {"id": "r1", "name": "api.example.com", "type": "A", "content": "192.0.2.1", "ttl": 3600, "proxied": False, "comment": ""},
        {"id": "r2", "name": "mail.example.com", "type": "MX", "content": "10 mail.example.com.", "ttl": 300, "proxied": False, "comment": ""},
    ]
    service.list_dns_records = MagicMock(return_value=mock_records)

    result = service.export_records("zone_123", format="bind")

    assert "api.example.com 3600 IN A 192.0.2.1" in result
    assert "mail.example.com 300 IN MX 10 mail.example.com." in result


def test_export_records_invalid_format_raises(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)
    service.list_dns_records = MagicMock(return_value=[])

    with pytest.raises(ValidationError, match="format"):
        service.export_records("zone_123", format="xml")


def test_export_records_empty_zone(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)
    service.list_dns_records = MagicMock(return_value=[])

    result = service.export_records("zone_123", format="csv")

    assert result.strip() == "name,type,content,ttl,proxied,comment"


# ── Import ────────────────────────────────────────────────────────────────────

CSV_CONTENT = """name,type,content,ttl,proxied,comment
api.example.com,A,192.0.2.1,3600,false,
www.example.com,CNAME,example.com,3600,true,CDN"""


def test_import_records_csv_dry_run_parses_records(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    result = service.import_records("zone_123", CSV_CONTENT, format="csv", dry_run=True)

    assert len(result) == 2
    assert result[0]["name"] == "api.example.com"
    assert result[0]["type"] == "A"
    assert result[0]["content"] == "192.0.2.1"
    assert result[0]["ttl"] == 3600
    assert result[0]["proxied"] is False
    assert result[1]["name"] == "www.example.com"
    assert result[1]["proxied"] is True
    assert result[1]["comment"] == "CDN"
    mock_cloudflare_client.sync_client.dns.records.create.assert_not_called()


def test_import_records_csv_creates_records(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    mock_record = MagicMock()
    mock_record.id = "new_r1"
    mock_record.name = "api.example.com"
    mock_record.type = "A"
    mock_record.content = "192.0.2.1"
    mock_record.ttl = 3600
    mock_cloudflare_client.sync_client.dns.records.create.return_value = mock_record

    single_row = "name,type,content,ttl,proxied,comment\napi.example.com,A,192.0.2.1,3600,false,"
    result = service.import_records("zone_123", single_row, format="csv", dry_run=False)

    assert len(result) == 1
    assert result[0]["id"] == "new_r1"
    mock_cloudflare_client.sync_client.dns.records.create.assert_called_once_with(
        zone_id="zone_123",
        name="api.example.com",
        type="A",
        content="192.0.2.1",
        ttl=3600,
        proxied=False,
    )


def test_import_records_csv_normalises_type_to_uppercase(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    csv = "name,type,content,ttl,proxied,comment\napi.example.com,a,192.0.2.1,3600,false,"
    result = service.import_records("zone_123", csv, format="csv", dry_run=True)

    assert result[0]["type"] == "A"


def test_import_records_bind_dry_run_parses_records(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    bind_content = """; Generated by cfmanager
api.example.com 3600 IN A 192.0.2.1
www.example.com 1 IN CNAME example.com"""

    result = service.import_records("zone_123", bind_content, format="bind", dry_run=True)

    assert len(result) == 2
    assert result[0]["name"] == "api.example.com"
    assert result[0]["type"] == "A"
    assert result[0]["ttl"] == 3600
    assert result[1]["type"] == "CNAME"
    assert result[1]["content"] == "example.com"
    mock_cloudflare_client.sync_client.dns.records.create.assert_not_called()


def test_import_records_bind_skips_comments_and_directives(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    bind_content = """; comment line
$ORIGIN example.com.
$TTL 3600
api.example.com 3600 IN A 192.0.2.1"""

    result = service.import_records("zone_123", bind_content, format="bind", dry_run=True)

    assert len(result) == 1
    assert result[0]["name"] == "api.example.com"


def test_import_records_invalid_format_raises(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    with pytest.raises(ValidationError, match="format"):
        service.import_records("zone_123", "data", format="xml", dry_run=True)


def test_import_records_csv_missing_required_fields_raises(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    bad_csv = "name,content\nexample.com,192.0.2.1"
    with pytest.raises(ValidationError, match="type"):
        service.import_records("zone_123", bad_csv, format="csv", dry_run=True)


def test_import_records_csv_missing_name_raises_validation_error(mock_cloudflare_client):
    service = DNSService(mock_cloudflare_client)

    bad_csv = "type,content,ttl\nA,192.0.2.1,3600"
    with pytest.raises(ValidationError, match="name"):
        service.import_records("zone_123", bad_csv, format="csv", dry_run=True)


def test_import_records_bind_four_token_ttl_line_skipped(mock_cloudflare_client):
    """A TTL-present BIND line with 4 tokens (no content) must be skipped, not produce empty content."""
    service = DNSService(mock_cloudflare_client)

    bind_content = """; valid line and one broken 4-token TTL-present line
api.example.com 3600 IN A 192.0.2.1
mail.example.com 300 IN A"""  # 4 tokens, else-branch, no content — must be skipped

    result = service.import_records("zone_123", bind_content, format="bind", dry_run=True)

    assert len(result) == 1
    assert result[0]["name"] == "api.example.com"
